export const FETCH_CATEGORIES_BEGIN = 'FETCH_CATEGORIES_BEGIN'; 
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'; 
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';

export const FETCH_IMAGES_BEGIN = 'FETCH_IMAGES_BEGIN'; 
export const FETCH_IMAGES_FAILURE = 'FETCH_IMAGES_FAILURE'; 
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';

export const POST_IMAGES_FAILURE = 'POST_IMAGES_FAILURE';
export const POST_IMAGES_SUCCESS = 'POST_IMAGES_SUCCESS';


export const GET_IMAGES_BY_CATEGORY_FAILURE = 'GET_IMAGES_BY_CATEGORY_FAILURE';
export const GET_IMAGES_BY_CATEGORY_SUCCESS = 'GET_IMAGES_BY_CATEGORY_SUCCESS';